#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ACCOUNTING_SYSTEM")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADM_REGISTRATION(ADM_REGISTRATION instance);
    partial void UpdateADM_REGISTRATION(ADM_REGISTRATION instance);
    partial void DeleteADM_REGISTRATION(ADM_REGISTRATION instance);
    partial void InsertMNG_CITY(MNG_CITY instance);
    partial void UpdateMNG_CITY(MNG_CITY instance);
    partial void DeleteMNG_CITY(MNG_CITY instance);
    partial void InsertMNG_LEDGER(MNG_LEDGER instance);
    partial void UpdateMNG_LEDGER(MNG_LEDGER instance);
    partial void DeleteMNG_LEDGER(MNG_LEDGER instance);
    partial void InsertMNG_ITEM_MASTER(MNG_ITEM_MASTER instance);
    partial void UpdateMNG_ITEM_MASTER(MNG_ITEM_MASTER instance);
    partial void DeleteMNG_ITEM_MASTER(MNG_ITEM_MASTER instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Accounting_System.Properties.Settings.Default.ACCOUNTING_SYSTEMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADM_LEDGER_REPORT> ADM_LEDGER_REPORTs
		{
			get
			{
				return this.GetTable<ADM_LEDGER_REPORT>();
			}
		}
		
		public System.Data.Linq.Table<ADM_LEDGER_TYPE> ADM_LEDGER_TYPEs
		{
			get
			{
				return this.GetTable<ADM_LEDGER_TYPE>();
			}
		}
		
		public System.Data.Linq.Table<MNG_COMPANY> MNG_COMPANies
		{
			get
			{
				return this.GetTable<MNG_COMPANY>();
			}
		}
		
		public System.Data.Linq.Table<MNG_PACK> MNG_PACKs
		{
			get
			{
				return this.GetTable<MNG_PACK>();
			}
		}
		
		public System.Data.Linq.Table<MNG_PURCHASE_CART> MNG_PURCHASE_CARTs
		{
			get
			{
				return this.GetTable<MNG_PURCHASE_CART>();
			}
		}
		
		public System.Data.Linq.Table<MNG_PURCHASE_PANEL> MNG_PURCHASE_PANELs
		{
			get
			{
				return this.GetTable<MNG_PURCHASE_PANEL>();
			}
		}
		
		public System.Data.Linq.Table<MNG_SALE_CART> MNG_SALE_CARTs
		{
			get
			{
				return this.GetTable<MNG_SALE_CART>();
			}
		}
		
		public System.Data.Linq.Table<MNG_SALE_PANEL> MNG_SALE_PANELs
		{
			get
			{
				return this.GetTable<MNG_SALE_PANEL>();
			}
		}
		
		public System.Data.Linq.Table<ADM_REGISTRATION> ADM_REGISTRATIONs
		{
			get
			{
				return this.GetTable<ADM_REGISTRATION>();
			}
		}
		
		public System.Data.Linq.Table<MNG_CITY> MNG_CITies
		{
			get
			{
				return this.GetTable<MNG_CITY>();
			}
		}
		
		public System.Data.Linq.Table<MNG_LEDGER> MNG_LEDGERs
		{
			get
			{
				return this.GetTable<MNG_LEDGER>();
			}
		}
		
		public System.Data.Linq.Table<MNG_ITEM_MASTER> MNG_ITEM_MASTERs
		{
			get
			{
				return this.GetTable<MNG_ITEM_MASTER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADM_LEDGER_REPORT")]
	public partial class ADM_LEDGER_REPORT
	{
		
		private int _ADM_LEDGER_REPORT_ID;
		
		private string _WINDOW;
		
		private string _ACCOUNT_NAME;
		
		private string _VOUCHER_NO;
		
		private string _VOUCHER_DATE;
		
		private string _DR;
		
		private string _CR;
		
		private string _BALANCE;
		
		public ADM_LEDGER_REPORT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADM_LEDGER_REPORT_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ADM_LEDGER_REPORT_ID
		{
			get
			{
				return this._ADM_LEDGER_REPORT_ID;
			}
			set
			{
				if ((this._ADM_LEDGER_REPORT_ID != value))
				{
					this._ADM_LEDGER_REPORT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WINDOW", DbType="VarChar(50)")]
		public string WINDOW
		{
			get
			{
				return this._WINDOW;
			}
			set
			{
				if ((this._WINDOW != value))
				{
					this._WINDOW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_NAME", DbType="VarChar(50)")]
		public string ACCOUNT_NAME
		{
			get
			{
				return this._ACCOUNT_NAME;
			}
			set
			{
				if ((this._ACCOUNT_NAME != value))
				{
					this._ACCOUNT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VOUCHER_NO", DbType="VarChar(50)")]
		public string VOUCHER_NO
		{
			get
			{
				return this._VOUCHER_NO;
			}
			set
			{
				if ((this._VOUCHER_NO != value))
				{
					this._VOUCHER_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VOUCHER_DATE", DbType="VarChar(50)")]
		public string VOUCHER_DATE
		{
			get
			{
				return this._VOUCHER_DATE;
			}
			set
			{
				if ((this._VOUCHER_DATE != value))
				{
					this._VOUCHER_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR", DbType="VarChar(50)")]
		public string DR
		{
			get
			{
				return this._DR;
			}
			set
			{
				if ((this._DR != value))
				{
					this._DR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CR", DbType="VarChar(50)")]
		public string CR
		{
			get
			{
				return this._CR;
			}
			set
			{
				if ((this._CR != value))
				{
					this._CR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BALANCE", DbType="VarChar(50)")]
		public string BALANCE
		{
			get
			{
				return this._BALANCE;
			}
			set
			{
				if ((this._BALANCE != value))
				{
					this._BALANCE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADM_LEDGER_TYPE")]
	public partial class ADM_LEDGER_TYPE
	{
		
		private int _ADM_LEDGER_TYPE_ID;
		
		private string _LEDGER_TYPE;
		
		private string _REMARKS;
		
		public ADM_LEDGER_TYPE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADM_LEDGER_TYPE_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ADM_LEDGER_TYPE_ID
		{
			get
			{
				return this._ADM_LEDGER_TYPE_ID;
			}
			set
			{
				if ((this._ADM_LEDGER_TYPE_ID != value))
				{
					this._ADM_LEDGER_TYPE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEDGER_TYPE", DbType="VarChar(50)")]
		public string LEDGER_TYPE
		{
			get
			{
				return this._LEDGER_TYPE;
			}
			set
			{
				if ((this._LEDGER_TYPE != value))
				{
					this._LEDGER_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="VarChar(50)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this._REMARKS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MNG_COMPANY")]
	public partial class MNG_COMPANY
	{
		
		private int _MNG_COMPANY_ID;
		
		private string _COMPANY_NAME;
		
		public MNG_COMPANY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNG_COMPANY_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MNG_COMPANY_ID
		{
			get
			{
				return this._MNG_COMPANY_ID;
			}
			set
			{
				if ((this._MNG_COMPANY_ID != value))
				{
					this._MNG_COMPANY_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_NAME", DbType="VarChar(50)")]
		public string COMPANY_NAME
		{
			get
			{
				return this._COMPANY_NAME;
			}
			set
			{
				if ((this._COMPANY_NAME != value))
				{
					this._COMPANY_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MNG_PACK")]
	public partial class MNG_PACK
	{
		
		private int _MNG_PACK_ID;
		
		private string _PACK;
		
		public MNG_PACK()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNG_PACK_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MNG_PACK_ID
		{
			get
			{
				return this._MNG_PACK_ID;
			}
			set
			{
				if ((this._MNG_PACK_ID != value))
				{
					this._MNG_PACK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACK", DbType="VarChar(50)")]
		public string PACK
		{
			get
			{
				return this._PACK;
			}
			set
			{
				if ((this._PACK != value))
				{
					this._PACK = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MNG_PURCHASE_CART")]
	public partial class MNG_PURCHASE_CART
	{
		
		private int _MNG_PURCHASE_CART_ID;
		
		private string _PURCHASE_CODE;
		
		private string _INVOICE_NO;
		
		private string _SUPPLIER_NAME;
		
		private string _PRODUCT_CODE;
		
		private string _PRODUCT_NAME;
		
		private string _HSN_CODE;
		
		private string _LANDING_PRICE;
		
		private string _SALLING_PRICE;
		
		private string _QNT;
		
		private string _DISCOUNT;
		
		private string _BEFORE_TAX;
		
		private string _CGST_PER;
		
		private string _CGST_VALUE;
		
		private string _SGST_PER;
		
		private string _SGST_VALUE;
		
		private string _IGST_PER;
		
		private string _IGST_VALUE;
		
		private string _TOTAL;
		
		public MNG_PURCHASE_CART()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNG_PURCHASE_CART_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MNG_PURCHASE_CART_ID
		{
			get
			{
				return this._MNG_PURCHASE_CART_ID;
			}
			set
			{
				if ((this._MNG_PURCHASE_CART_ID != value))
				{
					this._MNG_PURCHASE_CART_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PURCHASE_CODE", DbType="VarChar(50)")]
		public string PURCHASE_CODE
		{
			get
			{
				return this._PURCHASE_CODE;
			}
			set
			{
				if ((this._PURCHASE_CODE != value))
				{
					this._PURCHASE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INVOICE_NO", DbType="VarChar(50)")]
		public string INVOICE_NO
		{
			get
			{
				return this._INVOICE_NO;
			}
			set
			{
				if ((this._INVOICE_NO != value))
				{
					this._INVOICE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPPLIER_NAME", DbType="VarChar(50)")]
		public string SUPPLIER_NAME
		{
			get
			{
				return this._SUPPLIER_NAME;
			}
			set
			{
				if ((this._SUPPLIER_NAME != value))
				{
					this._SUPPLIER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_CODE", DbType="VarChar(50)")]
		public string PRODUCT_CODE
		{
			get
			{
				return this._PRODUCT_CODE;
			}
			set
			{
				if ((this._PRODUCT_CODE != value))
				{
					this._PRODUCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_NAME", DbType="VarChar(50)")]
		public string PRODUCT_NAME
		{
			get
			{
				return this._PRODUCT_NAME;
			}
			set
			{
				if ((this._PRODUCT_NAME != value))
				{
					this._PRODUCT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSN_CODE", DbType="VarChar(50)")]
		public string HSN_CODE
		{
			get
			{
				return this._HSN_CODE;
			}
			set
			{
				if ((this._HSN_CODE != value))
				{
					this._HSN_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANDING_PRICE", DbType="VarChar(50)")]
		public string LANDING_PRICE
		{
			get
			{
				return this._LANDING_PRICE;
			}
			set
			{
				if ((this._LANDING_PRICE != value))
				{
					this._LANDING_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALLING_PRICE", DbType="VarChar(50)")]
		public string SALLING_PRICE
		{
			get
			{
				return this._SALLING_PRICE;
			}
			set
			{
				if ((this._SALLING_PRICE != value))
				{
					this._SALLING_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QNT", DbType="VarChar(50)")]
		public string QNT
		{
			get
			{
				return this._QNT;
			}
			set
			{
				if ((this._QNT != value))
				{
					this._QNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNT", DbType="VarChar(50)")]
		public string DISCOUNT
		{
			get
			{
				return this._DISCOUNT;
			}
			set
			{
				if ((this._DISCOUNT != value))
				{
					this._DISCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEFORE_TAX", DbType="VarChar(50)")]
		public string BEFORE_TAX
		{
			get
			{
				return this._BEFORE_TAX;
			}
			set
			{
				if ((this._BEFORE_TAX != value))
				{
					this._BEFORE_TAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CGST_PER", DbType="VarChar(50)")]
		public string CGST_PER
		{
			get
			{
				return this._CGST_PER;
			}
			set
			{
				if ((this._CGST_PER != value))
				{
					this._CGST_PER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CGST_VALUE", DbType="VarChar(50)")]
		public string CGST_VALUE
		{
			get
			{
				return this._CGST_VALUE;
			}
			set
			{
				if ((this._CGST_VALUE != value))
				{
					this._CGST_VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGST_PER", DbType="VarChar(50)")]
		public string SGST_PER
		{
			get
			{
				return this._SGST_PER;
			}
			set
			{
				if ((this._SGST_PER != value))
				{
					this._SGST_PER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGST_VALUE", DbType="VarChar(50)")]
		public string SGST_VALUE
		{
			get
			{
				return this._SGST_VALUE;
			}
			set
			{
				if ((this._SGST_VALUE != value))
				{
					this._SGST_VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IGST_PER", DbType="VarChar(50)")]
		public string IGST_PER
		{
			get
			{
				return this._IGST_PER;
			}
			set
			{
				if ((this._IGST_PER != value))
				{
					this._IGST_PER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IGST_VALUE", DbType="VarChar(50)")]
		public string IGST_VALUE
		{
			get
			{
				return this._IGST_VALUE;
			}
			set
			{
				if ((this._IGST_VALUE != value))
				{
					this._IGST_VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="VarChar(50)")]
		public string TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this._TOTAL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MNG_PURCHASE_PANEL")]
	public partial class MNG_PURCHASE_PANEL
	{
		
		private int _MNG_PURCHASE_PANEL_ID;
		
		private string _PURCHASE_CODE;
		
		private string _PURCHASE_DATE;
		
		private string _INVOICE_NO;
		
		private string _INVOICE_DATE;
		
		private string _SUPPLIER_NAME;
		
		private string _TRA_NUMBER;
		
		private string _L_R_NO;
		
		private string _TRUCK_NO;
		
		private string _SUB_TOTAL;
		
		private string _DISCOUNT_TOTAL;
		
		private string _CGST_TOTAL;
		
		private string _SGST_TOTAL;
		
		private string _IGST_TOTAL;
		
		private string _INWORDS;
		
		private string _FREIGHT;
		
		private string _PACKING;
		
		private string _ROUND_OFF;
		
		private string _KASAR_VATAV;
		
		private string _GRAND_TOTAL;
		
		public MNG_PURCHASE_PANEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNG_PURCHASE_PANEL_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MNG_PURCHASE_PANEL_ID
		{
			get
			{
				return this._MNG_PURCHASE_PANEL_ID;
			}
			set
			{
				if ((this._MNG_PURCHASE_PANEL_ID != value))
				{
					this._MNG_PURCHASE_PANEL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PURCHASE_CODE", DbType="VarChar(50)")]
		public string PURCHASE_CODE
		{
			get
			{
				return this._PURCHASE_CODE;
			}
			set
			{
				if ((this._PURCHASE_CODE != value))
				{
					this._PURCHASE_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PURCHASE_DATE", DbType="VarChar(50)")]
		public string PURCHASE_DATE
		{
			get
			{
				return this._PURCHASE_DATE;
			}
			set
			{
				if ((this._PURCHASE_DATE != value))
				{
					this._PURCHASE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INVOICE_NO", DbType="VarChar(50)")]
		public string INVOICE_NO
		{
			get
			{
				return this._INVOICE_NO;
			}
			set
			{
				if ((this._INVOICE_NO != value))
				{
					this._INVOICE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INVOICE_DATE", DbType="VarChar(50)")]
		public string INVOICE_DATE
		{
			get
			{
				return this._INVOICE_DATE;
			}
			set
			{
				if ((this._INVOICE_DATE != value))
				{
					this._INVOICE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPPLIER_NAME", DbType="VarChar(50)")]
		public string SUPPLIER_NAME
		{
			get
			{
				return this._SUPPLIER_NAME;
			}
			set
			{
				if ((this._SUPPLIER_NAME != value))
				{
					this._SUPPLIER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRA_NUMBER", DbType="VarChar(50)")]
		public string TRA_NUMBER
		{
			get
			{
				return this._TRA_NUMBER;
			}
			set
			{
				if ((this._TRA_NUMBER != value))
				{
					this._TRA_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_R_NO", DbType="VarChar(50)")]
		public string L_R_NO
		{
			get
			{
				return this._L_R_NO;
			}
			set
			{
				if ((this._L_R_NO != value))
				{
					this._L_R_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRUCK_NO", DbType="VarChar(50)")]
		public string TRUCK_NO
		{
			get
			{
				return this._TRUCK_NO;
			}
			set
			{
				if ((this._TRUCK_NO != value))
				{
					this._TRUCK_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_TOTAL", DbType="VarChar(50)")]
		public string SUB_TOTAL
		{
			get
			{
				return this._SUB_TOTAL;
			}
			set
			{
				if ((this._SUB_TOTAL != value))
				{
					this._SUB_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNT_TOTAL", DbType="VarChar(50)")]
		public string DISCOUNT_TOTAL
		{
			get
			{
				return this._DISCOUNT_TOTAL;
			}
			set
			{
				if ((this._DISCOUNT_TOTAL != value))
				{
					this._DISCOUNT_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CGST_TOTAL", DbType="VarChar(50)")]
		public string CGST_TOTAL
		{
			get
			{
				return this._CGST_TOTAL;
			}
			set
			{
				if ((this._CGST_TOTAL != value))
				{
					this._CGST_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGST_TOTAL", DbType="VarChar(50)")]
		public string SGST_TOTAL
		{
			get
			{
				return this._SGST_TOTAL;
			}
			set
			{
				if ((this._SGST_TOTAL != value))
				{
					this._SGST_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IGST_TOTAL", DbType="VarChar(50)")]
		public string IGST_TOTAL
		{
			get
			{
				return this._IGST_TOTAL;
			}
			set
			{
				if ((this._IGST_TOTAL != value))
				{
					this._IGST_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INWORDS", DbType="VarChar(50)")]
		public string INWORDS
		{
			get
			{
				return this._INWORDS;
			}
			set
			{
				if ((this._INWORDS != value))
				{
					this._INWORDS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FREIGHT", DbType="VarChar(50)")]
		public string FREIGHT
		{
			get
			{
				return this._FREIGHT;
			}
			set
			{
				if ((this._FREIGHT != value))
				{
					this._FREIGHT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACKING", DbType="VarChar(50)")]
		public string PACKING
		{
			get
			{
				return this._PACKING;
			}
			set
			{
				if ((this._PACKING != value))
				{
					this._PACKING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROUND_OFF", DbType="VarChar(50)")]
		public string ROUND_OFF
		{
			get
			{
				return this._ROUND_OFF;
			}
			set
			{
				if ((this._ROUND_OFF != value))
				{
					this._ROUND_OFF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAR_VATAV", DbType="VarChar(50)")]
		public string KASAR_VATAV
		{
			get
			{
				return this._KASAR_VATAV;
			}
			set
			{
				if ((this._KASAR_VATAV != value))
				{
					this._KASAR_VATAV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRAND_TOTAL", DbType="VarChar(50)")]
		public string GRAND_TOTAL
		{
			get
			{
				return this._GRAND_TOTAL;
			}
			set
			{
				if ((this._GRAND_TOTAL != value))
				{
					this._GRAND_TOTAL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MNG_SALE_CART")]
	public partial class MNG_SALE_CART
	{
		
		private int _MNG_SALE_CART_ID;
		
		private string _INVOICE_NO;
		
		private string _CUSTOMER_CODE;
		
		private string _PRODUCT_CODE;
		
		private string _PRODUCT_NAME;
		
		private string _HSN_CODE;
		
		private string _MRP;
		
		private string _SALLING_PRICE;
		
		private string _QNT;
		
		private string _DISCOUNT;
		
		private string _BEFORE_TAX;
		
		private string _CGST_PER;
		
		private string _CGST_VALUE;
		
		private string _SGST_PER;
		
		private string _SGST_VALUE;
		
		private string _TOTAL;
		
		private string _SAVING;
		
		public MNG_SALE_CART()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNG_SALE_CART_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MNG_SALE_CART_ID
		{
			get
			{
				return this._MNG_SALE_CART_ID;
			}
			set
			{
				if ((this._MNG_SALE_CART_ID != value))
				{
					this._MNG_SALE_CART_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INVOICE_NO", DbType="VarChar(50)")]
		public string INVOICE_NO
		{
			get
			{
				return this._INVOICE_NO;
			}
			set
			{
				if ((this._INVOICE_NO != value))
				{
					this._INVOICE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_CODE", DbType="VarChar(50)")]
		public string CUSTOMER_CODE
		{
			get
			{
				return this._CUSTOMER_CODE;
			}
			set
			{
				if ((this._CUSTOMER_CODE != value))
				{
					this._CUSTOMER_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_CODE", DbType="VarChar(50)")]
		public string PRODUCT_CODE
		{
			get
			{
				return this._PRODUCT_CODE;
			}
			set
			{
				if ((this._PRODUCT_CODE != value))
				{
					this._PRODUCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_NAME", DbType="VarChar(50)")]
		public string PRODUCT_NAME
		{
			get
			{
				return this._PRODUCT_NAME;
			}
			set
			{
				if ((this._PRODUCT_NAME != value))
				{
					this._PRODUCT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSN_CODE", DbType="VarChar(50)")]
		public string HSN_CODE
		{
			get
			{
				return this._HSN_CODE;
			}
			set
			{
				if ((this._HSN_CODE != value))
				{
					this._HSN_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="VarChar(50)")]
		public string MRP
		{
			get
			{
				return this._MRP;
			}
			set
			{
				if ((this._MRP != value))
				{
					this._MRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALLING_PRICE", DbType="VarChar(50)")]
		public string SALLING_PRICE
		{
			get
			{
				return this._SALLING_PRICE;
			}
			set
			{
				if ((this._SALLING_PRICE != value))
				{
					this._SALLING_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QNT", DbType="VarChar(50)")]
		public string QNT
		{
			get
			{
				return this._QNT;
			}
			set
			{
				if ((this._QNT != value))
				{
					this._QNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNT", DbType="VarChar(50)")]
		public string DISCOUNT
		{
			get
			{
				return this._DISCOUNT;
			}
			set
			{
				if ((this._DISCOUNT != value))
				{
					this._DISCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEFORE_TAX", DbType="VarChar(50)")]
		public string BEFORE_TAX
		{
			get
			{
				return this._BEFORE_TAX;
			}
			set
			{
				if ((this._BEFORE_TAX != value))
				{
					this._BEFORE_TAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CGST_PER", DbType="VarChar(50)")]
		public string CGST_PER
		{
			get
			{
				return this._CGST_PER;
			}
			set
			{
				if ((this._CGST_PER != value))
				{
					this._CGST_PER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CGST_VALUE", DbType="VarChar(50)")]
		public string CGST_VALUE
		{
			get
			{
				return this._CGST_VALUE;
			}
			set
			{
				if ((this._CGST_VALUE != value))
				{
					this._CGST_VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGST_PER", DbType="VarChar(50)")]
		public string SGST_PER
		{
			get
			{
				return this._SGST_PER;
			}
			set
			{
				if ((this._SGST_PER != value))
				{
					this._SGST_PER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGST_VALUE", DbType="VarChar(50)")]
		public string SGST_VALUE
		{
			get
			{
				return this._SGST_VALUE;
			}
			set
			{
				if ((this._SGST_VALUE != value))
				{
					this._SGST_VALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="VarChar(50)")]
		public string TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this._TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVING", DbType="VarChar(50)")]
		public string SAVING
		{
			get
			{
				return this._SAVING;
			}
			set
			{
				if ((this._SAVING != value))
				{
					this._SAVING = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MNG_SALE_PANEL")]
	public partial class MNG_SALE_PANEL
	{
		
		private int _MNG_SALE_PANEL_ID;
		
		private string _INVOICE_NO;
		
		private string _INVOICE_DATE;
		
		private string _CUSTOMER_CODE;
		
		private string _CUSTOMER_NAME;
		
		private string _PAYMENT_TYPE;
		
		private string _PAID_AMT;
		
		private string _RTN_AMT;
		
		private string _SUB_TOTAL;
		
		private string _CGST_TOTAL;
		
		private string _SGST_TOTAL;
		
		private string _BILL_DISCOUNT;
		
		private string _TOTAL_SAVING;
		
		private string _TOTAL_QNT;
		
		private string _ROUND_OFF;
		
		private string _INWORDS;
		
		private string _GRAND_TOTAL;
		
		private string _EMPLOYEE_NAME;
		
		public MNG_SALE_PANEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNG_SALE_PANEL_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MNG_SALE_PANEL_ID
		{
			get
			{
				return this._MNG_SALE_PANEL_ID;
			}
			set
			{
				if ((this._MNG_SALE_PANEL_ID != value))
				{
					this._MNG_SALE_PANEL_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INVOICE_NO", DbType="VarChar(50)")]
		public string INVOICE_NO
		{
			get
			{
				return this._INVOICE_NO;
			}
			set
			{
				if ((this._INVOICE_NO != value))
				{
					this._INVOICE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INVOICE_DATE", DbType="VarChar(50)")]
		public string INVOICE_DATE
		{
			get
			{
				return this._INVOICE_DATE;
			}
			set
			{
				if ((this._INVOICE_DATE != value))
				{
					this._INVOICE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_CODE", DbType="VarChar(50)")]
		public string CUSTOMER_CODE
		{
			get
			{
				return this._CUSTOMER_CODE;
			}
			set
			{
				if ((this._CUSTOMER_CODE != value))
				{
					this._CUSTOMER_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="VarChar(50)")]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this._CUSTOMER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMENT_TYPE", DbType="VarChar(50)")]
		public string PAYMENT_TYPE
		{
			get
			{
				return this._PAYMENT_TYPE;
			}
			set
			{
				if ((this._PAYMENT_TYPE != value))
				{
					this._PAYMENT_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAID_AMT", DbType="VarChar(50)")]
		public string PAID_AMT
		{
			get
			{
				return this._PAID_AMT;
			}
			set
			{
				if ((this._PAID_AMT != value))
				{
					this._PAID_AMT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RTN_AMT", DbType="VarChar(50)")]
		public string RTN_AMT
		{
			get
			{
				return this._RTN_AMT;
			}
			set
			{
				if ((this._RTN_AMT != value))
				{
					this._RTN_AMT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_TOTAL", DbType="VarChar(50)")]
		public string SUB_TOTAL
		{
			get
			{
				return this._SUB_TOTAL;
			}
			set
			{
				if ((this._SUB_TOTAL != value))
				{
					this._SUB_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CGST_TOTAL", DbType="VarChar(50)")]
		public string CGST_TOTAL
		{
			get
			{
				return this._CGST_TOTAL;
			}
			set
			{
				if ((this._CGST_TOTAL != value))
				{
					this._CGST_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGST_TOTAL", DbType="VarChar(50)")]
		public string SGST_TOTAL
		{
			get
			{
				return this._SGST_TOTAL;
			}
			set
			{
				if ((this._SGST_TOTAL != value))
				{
					this._SGST_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BILL_DISCOUNT", DbType="VarChar(50)")]
		public string BILL_DISCOUNT
		{
			get
			{
				return this._BILL_DISCOUNT;
			}
			set
			{
				if ((this._BILL_DISCOUNT != value))
				{
					this._BILL_DISCOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_SAVING", DbType="VarChar(50)")]
		public string TOTAL_SAVING
		{
			get
			{
				return this._TOTAL_SAVING;
			}
			set
			{
				if ((this._TOTAL_SAVING != value))
				{
					this._TOTAL_SAVING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_QNT", DbType="VarChar(50)")]
		public string TOTAL_QNT
		{
			get
			{
				return this._TOTAL_QNT;
			}
			set
			{
				if ((this._TOTAL_QNT != value))
				{
					this._TOTAL_QNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROUND_OFF", DbType="VarChar(50)")]
		public string ROUND_OFF
		{
			get
			{
				return this._ROUND_OFF;
			}
			set
			{
				if ((this._ROUND_OFF != value))
				{
					this._ROUND_OFF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INWORDS", DbType="VarChar(50)")]
		public string INWORDS
		{
			get
			{
				return this._INWORDS;
			}
			set
			{
				if ((this._INWORDS != value))
				{
					this._INWORDS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRAND_TOTAL", DbType="VarChar(50)")]
		public string GRAND_TOTAL
		{
			get
			{
				return this._GRAND_TOTAL;
			}
			set
			{
				if ((this._GRAND_TOTAL != value))
				{
					this._GRAND_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_NAME", DbType="VarChar(50)")]
		public string EMPLOYEE_NAME
		{
			get
			{
				return this._EMPLOYEE_NAME;
			}
			set
			{
				if ((this._EMPLOYEE_NAME != value))
				{
					this._EMPLOYEE_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADM_REGISTRATION")]
	public partial class ADM_REGISTRATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ADM_REGISTRATION_ID;
		
		private string _NAME;
		
		private string _COMPANY_NAME;
		
		private string _MOBILE_NO;
		
		private string _EMAIL_ID;
		
		private string _USER_ID;
		
		private string _PASSWORD;
		
		private string _USER_TYPE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnADM_REGISTRATION_IDChanging(int value);
    partial void OnADM_REGISTRATION_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnCOMPANY_NAMEChanging(string value);
    partial void OnCOMPANY_NAMEChanged();
    partial void OnMOBILE_NOChanging(string value);
    partial void OnMOBILE_NOChanged();
    partial void OnEMAIL_IDChanging(string value);
    partial void OnEMAIL_IDChanged();
    partial void OnUSER_IDChanging(string value);
    partial void OnUSER_IDChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnUSER_TYPEChanging(string value);
    partial void OnUSER_TYPEChanged();
    #endregion
		
		public ADM_REGISTRATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADM_REGISTRATION_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ADM_REGISTRATION_ID
		{
			get
			{
				return this._ADM_REGISTRATION_ID;
			}
			set
			{
				if ((this._ADM_REGISTRATION_ID != value))
				{
					this.OnADM_REGISTRATION_IDChanging(value);
					this.SendPropertyChanging();
					this._ADM_REGISTRATION_ID = value;
					this.SendPropertyChanged("ADM_REGISTRATION_ID");
					this.OnADM_REGISTRATION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_NAME", DbType="VarChar(50)")]
		public string COMPANY_NAME
		{
			get
			{
				return this._COMPANY_NAME;
			}
			set
			{
				if ((this._COMPANY_NAME != value))
				{
					this.OnCOMPANY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._COMPANY_NAME = value;
					this.SendPropertyChanged("COMPANY_NAME");
					this.OnCOMPANY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILE_NO", DbType="VarChar(50)")]
		public string MOBILE_NO
		{
			get
			{
				return this._MOBILE_NO;
			}
			set
			{
				if ((this._MOBILE_NO != value))
				{
					this.OnMOBILE_NOChanging(value);
					this.SendPropertyChanging();
					this._MOBILE_NO = value;
					this.SendPropertyChanged("MOBILE_NO");
					this.OnMOBILE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_ID", DbType="VarChar(50)")]
		public string EMAIL_ID
		{
			get
			{
				return this._EMAIL_ID;
			}
			set
			{
				if ((this._EMAIL_ID != value))
				{
					this.OnEMAIL_IDChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_ID = value;
					this.SendPropertyChanged("EMAIL_ID");
					this.OnEMAIL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="VarChar(50)")]
		public string USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(50)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_TYPE", DbType="VarChar(50)")]
		public string USER_TYPE
		{
			get
			{
				return this._USER_TYPE;
			}
			set
			{
				if ((this._USER_TYPE != value))
				{
					this.OnUSER_TYPEChanging(value);
					this.SendPropertyChanging();
					this._USER_TYPE = value;
					this.SendPropertyChanged("USER_TYPE");
					this.OnUSER_TYPEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MNG_CITY")]
	public partial class MNG_CITY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MNG_CITY_ID;
		
		private string _CITY;
		
		private string _PIN_CODE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMNG_CITY_IDChanging(int value);
    partial void OnMNG_CITY_IDChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnPIN_CODEChanging(string value);
    partial void OnPIN_CODEChanged();
    #endregion
		
		public MNG_CITY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNG_CITY_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MNG_CITY_ID
		{
			get
			{
				return this._MNG_CITY_ID;
			}
			set
			{
				if ((this._MNG_CITY_ID != value))
				{
					this.OnMNG_CITY_IDChanging(value);
					this.SendPropertyChanging();
					this._MNG_CITY_ID = value;
					this.SendPropertyChanged("MNG_CITY_ID");
					this.OnMNG_CITY_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="VarChar(50)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN_CODE", DbType="VarChar(50)")]
		public string PIN_CODE
		{
			get
			{
				return this._PIN_CODE;
			}
			set
			{
				if ((this._PIN_CODE != value))
				{
					this.OnPIN_CODEChanging(value);
					this.SendPropertyChanging();
					this._PIN_CODE = value;
					this.SendPropertyChanged("PIN_CODE");
					this.OnPIN_CODEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MNG_LEDGER")]
	public partial class MNG_LEDGER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MNG_LEDGER_ID;
		
		private string _LEDGER_CODE;
		
		private string _LEDGER_NAME;
		
		private string _LEDGER_TYPE;
		
		private string _MOBILE_NO;
		
		private string _ADDRESS;
		
		private string _CITY;
		
		private string _GST_NO;
		
		private string _AADHAR_NO;
		
		private string _PAN_NO;
		
		private string _OPENING_BALANCE;
		
		private string _NARRATION;
		
		private string _ENTRY_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMNG_LEDGER_IDChanging(int value);
    partial void OnMNG_LEDGER_IDChanged();
    partial void OnLEDGER_CODEChanging(string value);
    partial void OnLEDGER_CODEChanged();
    partial void OnLEDGER_NAMEChanging(string value);
    partial void OnLEDGER_NAMEChanged();
    partial void OnLEDGER_TYPEChanging(string value);
    partial void OnLEDGER_TYPEChanged();
    partial void OnMOBILE_NOChanging(string value);
    partial void OnMOBILE_NOChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnGST_NOChanging(string value);
    partial void OnGST_NOChanged();
    partial void OnAADHAR_NOChanging(string value);
    partial void OnAADHAR_NOChanged();
    partial void OnPAN_NOChanging(string value);
    partial void OnPAN_NOChanged();
    partial void OnOPENING_BALANCEChanging(string value);
    partial void OnOPENING_BALANCEChanged();
    partial void OnNARRATIONChanging(string value);
    partial void OnNARRATIONChanged();
    partial void OnENTRY_DATEChanging(string value);
    partial void OnENTRY_DATEChanged();
    #endregion
		
		public MNG_LEDGER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNG_LEDGER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MNG_LEDGER_ID
		{
			get
			{
				return this._MNG_LEDGER_ID;
			}
			set
			{
				if ((this._MNG_LEDGER_ID != value))
				{
					this.OnMNG_LEDGER_IDChanging(value);
					this.SendPropertyChanging();
					this._MNG_LEDGER_ID = value;
					this.SendPropertyChanged("MNG_LEDGER_ID");
					this.OnMNG_LEDGER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEDGER_CODE", DbType="VarChar(50)")]
		public string LEDGER_CODE
		{
			get
			{
				return this._LEDGER_CODE;
			}
			set
			{
				if ((this._LEDGER_CODE != value))
				{
					this.OnLEDGER_CODEChanging(value);
					this.SendPropertyChanging();
					this._LEDGER_CODE = value;
					this.SendPropertyChanged("LEDGER_CODE");
					this.OnLEDGER_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEDGER_NAME", DbType="VarChar(50)")]
		public string LEDGER_NAME
		{
			get
			{
				return this._LEDGER_NAME;
			}
			set
			{
				if ((this._LEDGER_NAME != value))
				{
					this.OnLEDGER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LEDGER_NAME = value;
					this.SendPropertyChanged("LEDGER_NAME");
					this.OnLEDGER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEDGER_TYPE", DbType="VarChar(50)")]
		public string LEDGER_TYPE
		{
			get
			{
				return this._LEDGER_TYPE;
			}
			set
			{
				if ((this._LEDGER_TYPE != value))
				{
					this.OnLEDGER_TYPEChanging(value);
					this.SendPropertyChanging();
					this._LEDGER_TYPE = value;
					this.SendPropertyChanged("LEDGER_TYPE");
					this.OnLEDGER_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILE_NO", DbType="VarChar(50)")]
		public string MOBILE_NO
		{
			get
			{
				return this._MOBILE_NO;
			}
			set
			{
				if ((this._MOBILE_NO != value))
				{
					this.OnMOBILE_NOChanging(value);
					this.SendPropertyChanging();
					this._MOBILE_NO = value;
					this.SendPropertyChanged("MOBILE_NO");
					this.OnMOBILE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(50)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="VarChar(50)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GST_NO", DbType="VarChar(50)")]
		public string GST_NO
		{
			get
			{
				return this._GST_NO;
			}
			set
			{
				if ((this._GST_NO != value))
				{
					this.OnGST_NOChanging(value);
					this.SendPropertyChanging();
					this._GST_NO = value;
					this.SendPropertyChanged("GST_NO");
					this.OnGST_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AADHAR_NO", DbType="VarChar(50)")]
		public string AADHAR_NO
		{
			get
			{
				return this._AADHAR_NO;
			}
			set
			{
				if ((this._AADHAR_NO != value))
				{
					this.OnAADHAR_NOChanging(value);
					this.SendPropertyChanging();
					this._AADHAR_NO = value;
					this.SendPropertyChanged("AADHAR_NO");
					this.OnAADHAR_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAN_NO", DbType="VarChar(50)")]
		public string PAN_NO
		{
			get
			{
				return this._PAN_NO;
			}
			set
			{
				if ((this._PAN_NO != value))
				{
					this.OnPAN_NOChanging(value);
					this.SendPropertyChanging();
					this._PAN_NO = value;
					this.SendPropertyChanged("PAN_NO");
					this.OnPAN_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPENING_BALANCE", DbType="VarChar(50)")]
		public string OPENING_BALANCE
		{
			get
			{
				return this._OPENING_BALANCE;
			}
			set
			{
				if ((this._OPENING_BALANCE != value))
				{
					this.OnOPENING_BALANCEChanging(value);
					this.SendPropertyChanging();
					this._OPENING_BALANCE = value;
					this.SendPropertyChanged("OPENING_BALANCE");
					this.OnOPENING_BALANCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NARRATION", DbType="VarChar(50)")]
		public string NARRATION
		{
			get
			{
				return this._NARRATION;
			}
			set
			{
				if ((this._NARRATION != value))
				{
					this.OnNARRATIONChanging(value);
					this.SendPropertyChanging();
					this._NARRATION = value;
					this.SendPropertyChanged("NARRATION");
					this.OnNARRATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTRY_DATE", DbType="VarChar(50)")]
		public string ENTRY_DATE
		{
			get
			{
				return this._ENTRY_DATE;
			}
			set
			{
				if ((this._ENTRY_DATE != value))
				{
					this.OnENTRY_DATEChanging(value);
					this.SendPropertyChanging();
					this._ENTRY_DATE = value;
					this.SendPropertyChanged("ENTRY_DATE");
					this.OnENTRY_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MNG_ITEM_MASTER")]
	public partial class MNG_ITEM_MASTER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MNG_ITEM_MASTER_ID;
		
		private string _ITEM_CODE;
		
		private string _ITEM_NAME;
		
		private string _COMPANY_NAME;
		
		private string _PACK;
		
		private string _HSN_CODE;
		
		private string _MRP;
		
		private string _ITEM_LANDING_PRICE;
		
		private string _OPENING_STOCK;
		
		private string _CGST;
		
		private string _SGST;
		
		private string _DISCOUNT;
		
		private string _SALE_PRICE;
		
		private string _NARRATION;
		
		private string _ENTRY_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMNG_ITEM_MASTER_IDChanging(int value);
    partial void OnMNG_ITEM_MASTER_IDChanged();
    partial void OnITEM_CODEChanging(string value);
    partial void OnITEM_CODEChanged();
    partial void OnITEM_NAMEChanging(string value);
    partial void OnITEM_NAMEChanged();
    partial void OnCOMPANY_NAMEChanging(string value);
    partial void OnCOMPANY_NAMEChanged();
    partial void OnPACKChanging(string value);
    partial void OnPACKChanged();
    partial void OnHSN_CODEChanging(string value);
    partial void OnHSN_CODEChanged();
    partial void OnMRPChanging(string value);
    partial void OnMRPChanged();
    partial void OnITEM_LANDING_PRICEChanging(string value);
    partial void OnITEM_LANDING_PRICEChanged();
    partial void OnOPENING_STOCKChanging(string value);
    partial void OnOPENING_STOCKChanged();
    partial void OnCGSTChanging(string value);
    partial void OnCGSTChanged();
    partial void OnSGSTChanging(string value);
    partial void OnSGSTChanged();
    partial void OnDISCOUNTChanging(string value);
    partial void OnDISCOUNTChanged();
    partial void OnSALE_PRICEChanging(string value);
    partial void OnSALE_PRICEChanged();
    partial void OnNARRATIONChanging(string value);
    partial void OnNARRATIONChanged();
    partial void OnENTRY_DATEChanging(string value);
    partial void OnENTRY_DATEChanged();
    #endregion
		
		public MNG_ITEM_MASTER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MNG_ITEM_MASTER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MNG_ITEM_MASTER_ID
		{
			get
			{
				return this._MNG_ITEM_MASTER_ID;
			}
			set
			{
				if ((this._MNG_ITEM_MASTER_ID != value))
				{
					this.OnMNG_ITEM_MASTER_IDChanging(value);
					this.SendPropertyChanging();
					this._MNG_ITEM_MASTER_ID = value;
					this.SendPropertyChanged("MNG_ITEM_MASTER_ID");
					this.OnMNG_ITEM_MASTER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM_CODE", DbType="VarChar(50)")]
		public string ITEM_CODE
		{
			get
			{
				return this._ITEM_CODE;
			}
			set
			{
				if ((this._ITEM_CODE != value))
				{
					this.OnITEM_CODEChanging(value);
					this.SendPropertyChanging();
					this._ITEM_CODE = value;
					this.SendPropertyChanged("ITEM_CODE");
					this.OnITEM_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM_NAME", DbType="VarChar(50)")]
		public string ITEM_NAME
		{
			get
			{
				return this._ITEM_NAME;
			}
			set
			{
				if ((this._ITEM_NAME != value))
				{
					this.OnITEM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ITEM_NAME = value;
					this.SendPropertyChanged("ITEM_NAME");
					this.OnITEM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_NAME", DbType="VarChar(50)")]
		public string COMPANY_NAME
		{
			get
			{
				return this._COMPANY_NAME;
			}
			set
			{
				if ((this._COMPANY_NAME != value))
				{
					this.OnCOMPANY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._COMPANY_NAME = value;
					this.SendPropertyChanged("COMPANY_NAME");
					this.OnCOMPANY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACK", DbType="VarChar(50)")]
		public string PACK
		{
			get
			{
				return this._PACK;
			}
			set
			{
				if ((this._PACK != value))
				{
					this.OnPACKChanging(value);
					this.SendPropertyChanging();
					this._PACK = value;
					this.SendPropertyChanged("PACK");
					this.OnPACKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSN_CODE", DbType="VarChar(50)")]
		public string HSN_CODE
		{
			get
			{
				return this._HSN_CODE;
			}
			set
			{
				if ((this._HSN_CODE != value))
				{
					this.OnHSN_CODEChanging(value);
					this.SendPropertyChanging();
					this._HSN_CODE = value;
					this.SendPropertyChanged("HSN_CODE");
					this.OnHSN_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="VarChar(50)")]
		public string MRP
		{
			get
			{
				return this._MRP;
			}
			set
			{
				if ((this._MRP != value))
				{
					this.OnMRPChanging(value);
					this.SendPropertyChanging();
					this._MRP = value;
					this.SendPropertyChanged("MRP");
					this.OnMRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEM_LANDING_PRICE", DbType="VarChar(50)")]
		public string ITEM_LANDING_PRICE
		{
			get
			{
				return this._ITEM_LANDING_PRICE;
			}
			set
			{
				if ((this._ITEM_LANDING_PRICE != value))
				{
					this.OnITEM_LANDING_PRICEChanging(value);
					this.SendPropertyChanging();
					this._ITEM_LANDING_PRICE = value;
					this.SendPropertyChanged("ITEM_LANDING_PRICE");
					this.OnITEM_LANDING_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPENING_STOCK", DbType="VarChar(50)")]
		public string OPENING_STOCK
		{
			get
			{
				return this._OPENING_STOCK;
			}
			set
			{
				if ((this._OPENING_STOCK != value))
				{
					this.OnOPENING_STOCKChanging(value);
					this.SendPropertyChanging();
					this._OPENING_STOCK = value;
					this.SendPropertyChanged("OPENING_STOCK");
					this.OnOPENING_STOCKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CGST", DbType="VarChar(50)")]
		public string CGST
		{
			get
			{
				return this._CGST;
			}
			set
			{
				if ((this._CGST != value))
				{
					this.OnCGSTChanging(value);
					this.SendPropertyChanging();
					this._CGST = value;
					this.SendPropertyChanged("CGST");
					this.OnCGSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGST", DbType="VarChar(50)")]
		public string SGST
		{
			get
			{
				return this._SGST;
			}
			set
			{
				if ((this._SGST != value))
				{
					this.OnSGSTChanging(value);
					this.SendPropertyChanging();
					this._SGST = value;
					this.SendPropertyChanged("SGST");
					this.OnSGSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNT", DbType="VarChar(50)")]
		public string DISCOUNT
		{
			get
			{
				return this._DISCOUNT;
			}
			set
			{
				if ((this._DISCOUNT != value))
				{
					this.OnDISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNT = value;
					this.SendPropertyChanged("DISCOUNT");
					this.OnDISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALE_PRICE", DbType="VarChar(50)")]
		public string SALE_PRICE
		{
			get
			{
				return this._SALE_PRICE;
			}
			set
			{
				if ((this._SALE_PRICE != value))
				{
					this.OnSALE_PRICEChanging(value);
					this.SendPropertyChanging();
					this._SALE_PRICE = value;
					this.SendPropertyChanged("SALE_PRICE");
					this.OnSALE_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NARRATION", DbType="VarChar(50)")]
		public string NARRATION
		{
			get
			{
				return this._NARRATION;
			}
			set
			{
				if ((this._NARRATION != value))
				{
					this.OnNARRATIONChanging(value);
					this.SendPropertyChanging();
					this._NARRATION = value;
					this.SendPropertyChanged("NARRATION");
					this.OnNARRATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTRY_DATE", DbType="VarChar(50)")]
		public string ENTRY_DATE
		{
			get
			{
				return this._ENTRY_DATE;
			}
			set
			{
				if ((this._ENTRY_DATE != value))
				{
					this.OnENTRY_DATEChanging(value);
					this.SendPropertyChanging();
					this._ENTRY_DATE = value;
					this.SendPropertyChanged("ENTRY_DATE");
					this.OnENTRY_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
